apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://api:8000/metrics
    isDefault: false
    jsonData:
      httpMethod: GET
  - name: SolarSpongeAPI
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://api:8000
    isDefault: true
